"""new fields in user model

Revision ID: 03854c73fd47
Revises: 52d448414bff
Create Date: 2020-03-08 09:47:57.521314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03854c73fd47'
down_revision = '52d448414bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
